/* Generated by tex3ds */
#pragma once

#define backgrounds_river_crossing_idx 0
#define backgrounds_snow_mountains_2_idx 1
#define backgrounds_snow_mountains_idx 2
#define backgrounds_snow_river_idx 3
#define backgrounds_main_idx 4
#define backgrounds_snow_road_idx 5
#define backgrounds_mountains_idx 6
