/* Generated by tex3ds */
#pragma once

#define ui_buttons_cara_title_idx 0
#define ui_buttons_ephrata_title_idx 1
#define ui_buttons_kalama_title_idx 2
#define ui_buttons_pause_title_idx 3
#define ui_buttons_selection_box_idx 4
#define ui_buttons_001_singleplayer_idx 5
#define ui_buttons_multiplayer_idx 6
#define ui_buttons_options_idx 7
#define ui_buttons_quit_idx 8
#define ui_buttons_textbox_idx 9
#define ui_buttons_textbox_background_idx 10
